# Likert single stimulus page 1 stimuli, 4 responses


testname: Likert Single Stimulus with four responses
testId: lss_4scale
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php



pages:

    - type: likert_single_stimulus
      id: lss2
      name: likert
      content: test description
      stimuli:
          C1: configs/resources/audio/mono_c1.wav
      response:
        - value: not at all
          label: Not at all
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: not a lot
          label: Not a lot
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: a bit
          label: A bit
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: much
          label: Much
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png          


    - type: finish
      name: Thank you
      content: Thank you for attending
      showResults: true
      writeResults: true
