testname: Localization test
testId: spatial
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: false
remoteService: service/write.php
pages:
    - type: generic
      id: first_page
      name: Welcome
      content: This is an example test for the evaluation of spatial attributes. On the following pages you will find examples for the evaluation of: <ul><li>Apparent/Auditory Source Width (ASW)</li><li>Listener's Envelopment (LEV)</li><li>Height, width and depth of a stimulus</li><li>Localization of sound sources</li></ul> The test will also give you an overview of the different views that can be used. </br>On the last page will be a short questionnaire to get to know some properties about the participant.</br></br>Push the 'NEXT'-Button to start with this example experiment! 
    - type: spatial
      id : test_page
      name: Apparent/Auditory Source Width (ASW) and Listener's Envelopement (LEV)
      content: On this page you have to evaluate the ASW and LEV of the stimulus. You can play back the stimulus by pressing the play button. Afterwards chose the object you want to adjust, to your personal perception of the stimulus, by pressing the according button. Select the Drag and Drop Control Elements (little spheres) and move them to your desired position. When you are finished push the 'NEXT'- Button!  
      framerate: 40
      roomMeasurements: [600, 240, 500] # width, height, length
      stimuli:
          C1: configs/resources/audio/mono_c1.wav       
      responses:
        - type: lev
          name: lev1
          label: LEV
          color: 0xbb0000      
          stimulus: C1    
          position: [0,50,0]
          size: [100,100,50]
        - type: asw
          name: asw1
          label: ASW1
          color: 0x123456
          stimulus: C1
          bezierOuterLeft: [100,0,-50]
          bezierInnerLeft: [50,0,-100]
          bezierInnerRight: [-50,0,-100]
          bezierOuterRight: [-100,0,-50]
      views: 
        - view: front
        - view: top
          position: [400,50,400]
      objects: 
        - type: listener
          position: [0,100,0]
          rotation: [0,0,180]
        - type: custom
          path: lib/webmushra/spatial/resources/listener_head.dae
          position: [0,50,0]
          rotation: [0,0,180]
          scale: 5
    - type: spatial
      id : test_page
      name: Perceived height, width and depth (HWD) of a stimulus 
      content: Here you have to rate the height, width and depth of two stimuli. So play back one of the stimuli and push the button of the according HWD element. To adjust the height, width and depth move the drag and drop elements! To change the depth and height use the two control points in the middle of the curve, to change the width and form move the 4 control points of the control polygon. You can use the 2D views to adjust the HWD element, the 3D View is just for a better overview.
      framerate: 100
      roomMeasurements: [600, 240, 500] # width, height, length
      stimuli:
          C1: configs/resources/audio/mono_c1.wav
          C2: configs/resources/audio/mono_c2.wav
      responses:
        - type: hwd
          name: hwd1
          label: HWD1
          color: 0xff7029
          stimulus: C2
          bezierOuterLeft: [-200,100,-50]
          bezierInnerLeft: [-50,100,-100]
          bezierInnerRight: [50,100,-100]
          bezierOuterRight: [200,100,-50]
          height: 100
          depth: 50
        - type: hwd
          name: hwd2
          label: HWD2
          color: 0x3300ff
          stimulus: C1
          bezierOuterLeft: [-150,100,100]
          bezierInnerLeft: [-40,100,150]
          bezierInnerRight: [40,100,150]
          bezierOuterRight: [150,100,100]
          height: 50
          depth: 30
      views: 
        - view: right
        - view: top
        - view: 3d
          position: [400,50,400]
      objects: 
        - type: listener
          position: [0,100,0]
          rotation: [0,0,180]
        - type: custom
          path: lib/webmushra/spatial/resources/listener_head.dae
          position: [0,50,0]
          rotation: [0,0,180]
          scale: 5
    - type: spatial
      id : test_page
      name: Localization of a stimulus
      content: Now you have to locate different stimuli. Play back a stimulus and place the spheres, with the colors of the buttons in the according box with the player, to the positions where you perceive sound sources. The number of spheres should fit the number of perceived sound sources and it is not important which sphere represents which sound source. Place the spheres simply by clicking into the scene (here you can also use the 3D view to place the spheres)!
      framerate: 100
      roomMeasurements: [600, 240, 500] # width, height, length
      stimuli:
          C1: configs/resources/audio/mono_c1.wav
          C2: configs/resources/audio/mono_c2.wav
          C3: configs/resources/audio/mono_c3.wav
      responses:
        - type: localization
          name: locA
          label: A
          color: 0xff0000
          stimulus: C1    
          position: [100,100,0]
          size: 20
        - type: localization
          name: locB
          label: B
          color: 0xff5500      
          stimulus: C1    
          position: [-100,100,0]
          size: 20
        - type: localization
          name: locC
          label: C
          color: 0x00ff00      
          stimulus: C2    
          position: [50,50,0]
          size: 10
        - type: localization
          name: locD
          label: D
          color: 0x00ff88      
          stimulus: C2    
          position: [0,50,0]
          size: 10
        - type: localization
          name: locE
          label: E
          color: 0x00ffee      
          stimulus: C2    
          position: [-50,50,0]
          size: 10
        - type: localization
          name: locF
          label: F
          color: 0x0000ff      
          stimulus: C3    
          position: [0,100,-100]
          size: 10
      views: 
        - view: front
        - view: top
        - view: 3d
          position: [400,50,-400]
      objects: 
        - type: listener
          position: [0,100,0]
          rotation: [0,0,180]
        - type: custom
          path: lib/webmushra/spatial/resources/listener_head.dae
          position: [0,50,0]
          rotation: [0,0,180]
          scale: 5
    - type: finish
      name: Thank you
      content: Thank you for attending
      showResults: false
      writeResults: true
      questionnaire:
          - type: text
            label: name/shortname/nickname
            name: email
          - type: number
            label: Age
            name: age
            min: 0
            max: 100
            default: 30
          - type: likert
            name: gender
            label: Gender
            response:
             - value: female
               label: Female
             - value: male
               label: Male
             - value: other
               label: Other
          - type: likert
            name: expert_timbre
            label: Are you an expert listener in judging timbre? 
            response:
             - value: no
               label: No
             - value: yes
               label: Yes
          - type: likert
            name: expert_spatial
            label: Are you an expert listener in spatial audio? 
            response:
             - value: no
               label: No
             - value: yes
               label: Yes
          - type: likert
            name: listening_test_experience
            label: Have you taken part in a listening test about spatial attributes yet? 
            response:
             - value: no
               label: No
             - value: yes
               label: Yes
          - type: likert
            name: professional
            label: Do you have a background in professional audio (e.g. sound/recording engineer, researcher)? 
            response:
             - value: no
               label: No
             - value: yes
               label: Yes
